# Generated by Django 2.0.7 on 2018-08-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180813_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='description',
            new_name='comment',
        ),
    ]
