# Generated by Django 2.0.7 on 2018-08-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180814_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='blog_title',
        ),
    ]
