# Generated by Django 2.0.7 on 2018-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180816_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='Enter your blog text here.', max_length=2001),
        ),
    ]
